name: mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # L10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  easy_localization: ^3.0.1

  # Architecture, DI
  flutter_riverpod: ^2.2.0
  riverpod_annotation: ^2.1.1

  # Networking
  dio: ^5.2.1+1

  # UI
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_markdown: ^0.6.14
  flutter_portal: ^1.1.3
  flutter_svg: ^2.0.2
  infinite_scroll_pagination: ^3.2.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0

  # Routing
  auto_route: ^7.6.0
  cupertino_icons: ^1.0.5

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Local storage
  shared_preferences: ^2.0.18

  # Utils
  collection: ^1.16.0
  flutter_launcher_icons: ^0.13.1
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.1.1
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.2.0
  riverpod_generator: ^2.2.3
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  intl: ^0.18.1

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
